server:
  port: 8082

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: c##test
    password: MyPass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
